version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hirebot-api-dev
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - dev_tools
    stdin_open: true
    tty: true

networks:
  dev_tools:
    external: true
