version: '3.8'

services:
  # Redis service
  redis:
    image: redis:latest
    container_name: hirebot_redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - '${REDIS_PORT:-6379}:6379'
    networks:
      - hirebot_network
    # No port mapping to host, only internal exposure

  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: hirebot_mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - '${MONGODB_PORT:-27017}:27017'
    networks:
      - hirebot_network
    # No port mapping to host, only internal exposure

  # Node.js application service
  nodejs_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hirebot_nodejs
    restart: always
    depends_on:
      - redis
      - mongodb
    networks:
      - hirebot_network
    env_file:
      - .env
    environment:
      - NODE_ENV=production

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: hirebot_nginx
    restart: always
    ports:
      - '${APP_PORT:-8000}:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodejs_app
    networks:
      - hirebot_network

networks:
  hirebot_network:
    driver: bridge

volumes:
  redis_data:
  mongodb_data:
