services:
  hirebot_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '${APP_PORT:-8000}:3000'
    env_file:
      - .env
    networks:
      - dev_tools

networks:
  dev_tools:
    external: true
